# Generated by Django 5.0.14 on 2025-12-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_editlock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='editlock',
            new_name='patients_ed_patient_499926_idx',
            old_name='patients_ed_patient_5a8f2a_idx',
        ),
    ]
