# Generated by Django 5.0.14 on 2025-12-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada'), ('OVERDUE', 'Vencida')], default='DRAFT', max_length=20),
        ),
    ]
