# Generated by Django 5.0.14 on 2025-12-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_notification_appointment_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_professional_slot',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_room_slot',
        ),
    ]
