# Generated by Django 5.0.14 on 2025-12-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_unique_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentEditLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_lock', to='appointments.appointment')),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-locked_at'],
                'indexes': [models.Index(fields=['appointment', 'expires_at'], name='appointment_appoint_99ecd1_idx')],
            },
        ),
    ]
