# Generated by Django 5.0.14 on 2025-11-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=120)),
                ('license_number', models.CharField(max_length=80, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('working_days', models.CharField(help_text='Días disponibles. Ej: LUN-VIE', max_length=64)),
                ('start_hour', models.TimeField(blank=True, null=True)),
                ('end_hour', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
