# Generated by Django 5.0.14 on 2025-12-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Ocupada'), ('MAINTENANCE', 'Mantenimiento')], default='AVAILABLE', max_length=20),
        ),
    ]
