# Generated by Django 5.0.14 on 2025-12-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='equipment',
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='resources.equipment'),
        ),
    ]
