# Generated by Django 5.0.14 on 2025-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_room_equipment_room_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('MAINTENANCE', 'Mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de servicio')], default='AVAILABLE', max_length=20),
        ),
    ]
