# Generated by Django 5.0.14 on 2025-12-04 09:28

from django.db import migrations, models


def clean_duplicate_document_ids(apps, schema_editor):
    """Limpiar DNIs duplicados antes de aplicar la restricción única"""
    User = apps.get_model('users', 'User')
    seen = set()
    for user in User.objects.exclude(document_id__isnull=True).exclude(document_id=''):
        if user.document_id in seen:
            # Si ya existe, limpiar el DNI duplicado
            user.document_id = ''
            user.save(update_fields=['document_id'])
        else:
            seen.add(user.document_id)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_document_ids, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='document_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        # Nota: La validación de DNI único se hace en el serializer
        # El constraint de base de datos se puede añadir más tarde si es necesario
    ]
