# Generated by Django 5.0.14 on 2025-12-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_document_id_and_more'),
    ]

    operations = [
    ]
