# Generated by Django 5.0.14 on 2025-12-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_clean_duplicate_dnis'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('document_id__isnull', False)), fields=('document_id',), name='unique_document_id'),
        ),
    ]
